app:
  datasource:
    jdbc-url: jdbc:postgresql://localhost:5432/birdspostgresdb
    username: postgres
    password: P@ssw0rd
    pool-size: 30
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
